export const THINGS_RECEIVED = 'THINGS_RECEIVED'
export const THING_DELETED = 'THING_DELETED'
export const THING_UPDATED = 'THING_UPDATED'
export const THING_CREATED = 'THING_CREATED'

export const ACTION_SENT = 'ACTION_SENT'
export const ACTION_DONE = 'ACTION_DONE'
export const GETTER_SENT = 'GETTER_SENT'

export const SNACKBAR_CLOSED = 'SNACKBAR_CLOSED'
